import { useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Zap, Plus, Library, Settings, LogOut, ChevronDown, Copy, Download,
  FileText, Youtube, Globe, Sparkles, BarChart3, Clock, Flame,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const summaryFormats = [
  "Quick Summary",
  "Detailed Summary",
  "Bullet Points",
  "Study Mode",
  "Mindmap Style",
  "Twitter Thread",
];

const mockSummaries = [
  { id: 1, title: "How AI is Changing Education", type: "video", format: "Bullet Points", date: "2 hours ago" },
  { id: 2, title: "React Best Practices 2026", type: "article", format: "Quick Summary", date: "Yesterday" },
  { id: 3, title: "Machine Learning Research Paper", type: "pdf", format: "Study Mode", date: "2 days ago" },
];

const typeIcon = { video: Youtube, article: Globe, pdf: FileText };

export default function Dashboard() {
  const [activeTab, setActiveTab] = useState("generate");
  const [contentUrl, setContentUrl] = useState("");
  const [format, setFormat] = useState("Quick Summary");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedSummary, setGeneratedSummary] = useState("");

  const handleGenerate = () => {
    if (!contentUrl) return;
    setIsGenerating(true);
    setGeneratedSummary("");
    setTimeout(() => {
      setIsGenerating(false);
      setGeneratedSummary(
        `## Quick Summary\n\nThis is a demo summary of the content you provided. In the full version, Snapysummary's AI will analyze the content and produce a high-quality summary tailored to your chosen format.\n\n**Key Points:**\n- Point one: Important insight from the content\n- Point two: Another key takeaway\n- Point three: Final notable detail\n\n*Generated by Snapysummary AI*`
      );
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-background flex">
      {/* Sidebar */}
      <aside className="hidden lg:flex w-64 border-r border-border flex-col bg-card">
        <div className="p-4 border-b border-border">
          <Link to="/" className="flex items-center gap-2">
            <Zap className="h-6 w-6 text-primary" />
            <span className="text-lg font-bold">Snapysummary</span>
          </Link>
        </div>
        <nav className="flex-1 p-3 space-y-1">
          {[
            { icon: Plus, label: "Generate", tab: "generate" },
            { icon: Library, label: "My Library", tab: "library" },
            { icon: BarChart3, label: "Analytics", tab: "analytics" },
            { icon: Settings, label: "Settings", tab: "settings" },
          ].map((item) => (
            <button
              key={item.tab}
              onClick={() => setActiveTab(item.tab)}
              className={`w-full flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${
                activeTab === item.tab
                  ? "bg-primary/10 text-primary"
                  : "text-muted-foreground hover:bg-accent hover:text-foreground"
              }`}
            >
              <item.icon className="h-4 w-4" />
              {item.label}
            </button>
          ))}
        </nav>
        <div className="p-3 border-t border-border">
          <Button variant="ghost" className="w-full justify-start gap-3 text-muted-foreground" asChild>
            <Link to="/"><LogOut className="h-4 w-4" /> Log out</Link>
          </Button>
        </div>
      </aside>

      {/* Main */}
      <main className="flex-1 flex flex-col">
        {/* Top bar */}
        <header className="h-16 border-b border-border flex items-center justify-between px-6">
          <div className="flex items-center gap-3">
            <div className="lg:hidden flex items-center gap-2">
              <Zap className="h-5 w-5 text-primary" />
              <span className="font-bold">Snapysummary</span>
            </div>
            <div className="hidden sm:flex items-center gap-2 text-sm">
              <span className="text-muted-foreground">Hello,</span>
              <span className="font-semibold">User</span>
              <span className="flex items-center gap-1 text-primary ml-2"><Flame className="h-4 w-4" /> 5 day streak</span>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium">3 credits left</span>
              <Progress value={100} className="w-20 h-2" />
            </div>
            <Button size="sm" asChild>
              <Link to="/upgrade">Upgrade</Link>
            </Button>
          </div>
        </header>

        {/* Content */}
        <div className="flex-1 p-6 overflow-y-auto">
          {activeTab === "generate" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="max-w-3xl mx-auto space-y-6">
              <div>
                <h2 className="text-2xl font-bold mb-1">Generate Summary</h2>
                <p className="text-sm text-muted-foreground">Paste a URL or upload a PDF to get started</p>
              </div>

              <div className="rounded-2xl border border-border p-6 bg-card space-y-4">
                <div className="flex gap-3">
                  <div className="flex-1">
                    <Input
                      placeholder="Paste YouTube, article, or blog URL..."
                      value={contentUrl}
                      onChange={(e) => setContentUrl(e.target.value)}
                      className="h-12"
                    />
                  </div>
                  <Button variant="outline" className="h-12 px-4">
                    <FileText className="h-4 w-4 mr-2" /> Upload PDF
                  </Button>
                </div>
                <div className="flex gap-3 items-end">
                  <div className="flex-1">
                    <label className="text-sm font-medium mb-1.5 block">Summary Format</label>
                    <Select value={format} onValueChange={setFormat}>
                      <SelectTrigger className="h-10"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        {summaryFormats.map((f) => (
                          <SelectItem key={f} value={f}>{f}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <Button className="h-10 px-6 shadow-glow" onClick={handleGenerate} disabled={isGenerating || !contentUrl}>
                    {isGenerating ? (
                      <><Clock className="h-4 w-4 mr-2 animate-spin" /> Generating...</>
                    ) : (
                      <><Sparkles className="h-4 w-4 mr-2" /> Generate</>
                    )}
                  </Button>
                </div>
              </div>

              {isGenerating && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="rounded-2xl border border-border p-8 bg-card text-center">
                  <div className="animate-float inline-block mb-4">
                    <Sparkles className="h-10 w-10 text-primary" />
                  </div>
                  <p className="text-muted-foreground">Processing with AI... This usually takes a few seconds.</p>
                </motion.div>
              )}

              {generatedSummary && !isGenerating && (
                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="rounded-2xl border border-border p-6 bg-card">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="font-semibold">Your Summary</h3>
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm"><Copy className="h-3.5 w-3.5 mr-1" /> Copy</Button>
                      <Button variant="outline" size="sm"><Download className="h-3.5 w-3.5 mr-1" /> Export</Button>
                    </div>
                  </div>
                  <div className="prose prose-sm max-w-none text-foreground">
                    {generatedSummary.split("\n").map((line, i) => (
                      <p key={i} className={line.startsWith("##") ? "text-lg font-semibold" : line.startsWith("**") ? "font-medium" : line.startsWith("- ") ? "ml-4" : ""}>{line.replace(/^[#*-]+\s?/g, "")}</p>
                    ))}
                  </div>
                </motion.div>
              )}
            </motion.div>
          )}

          {activeTab === "library" && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="max-w-4xl mx-auto">
              <h2 className="text-2xl font-bold mb-6">My Library</h2>
              <div className="space-y-3">
                {mockSummaries.map((s) => {
                  const Icon = typeIcon[s.type as keyof typeof typeIcon];
                  return (
                    <div key={s.id} className="rounded-xl border border-border p-4 bg-card flex items-center gap-4 hover:shadow-md transition-shadow cursor-pointer">
                      <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                        <Icon className="h-5 w-5 text-primary" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="font-medium truncate">{s.title}</p>
                        <p className="text-xs text-muted-foreground">{s.format} · {s.date}</p>
                      </div>
                      <Button variant="ghost" size="sm"><Copy className="h-4 w-4" /></Button>
                    </div>
                  );
                })}
              </div>
            </motion.div>
          )}

          {(activeTab === "analytics" || activeTab === "settings") && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="max-w-3xl mx-auto text-center py-20">
              <Sparkles className="h-12 w-12 text-primary mx-auto mb-4" />
              <h2 className="text-2xl font-bold mb-2">Coming Soon</h2>
              <p className="text-muted-foreground">This feature will be available when backend is connected.</p>
            </motion.div>
          )}
        </div>
      </main>
    </div>
  );
}
